# Generated by Django 2.0.5 on 2018-05-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='trainee', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('identity_type', models.CharField(default='account', max_length=20)),
                ('indentifer', models.CharField(max_length=20)),
                ('credential', models.CharField(max_length=20)),
            ],
        ),
    ]
